<?php

namespace App\Repository\Shared;

use Doctrine\ORM\EntityRepository;
use App\Entity\Shared\Company;

/**
 * CompanyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * @param array|Company[] $companies
     *
     * @return array|Company[]
     */
    public function findOther(array $companies)
    {
        return $this->createOtherQueryBuilder($companies)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param array $companies
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createOtherQueryBuilder(array $companies)
    {
        $ids = array_map(function (Company $company) {
            return $company->getId();
        }, $companies);

        $qb = $this->createQueryBuilder('c');
        $qb->andWhere('c.deleted = :deleted or c.deleted is null');
        $qb->setParameter('deleted', false);

        if (!empty($ids)) {
            $expr = $this->getEntityManager()->getExpressionBuilder();
            $qb->andWhere($expr->notIn('c.id', $ids));
        }

        return $qb;
    }
}
