<?php

namespace App\Repository\Shared;

/**
 * LicencedCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencedCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
