version: '3.5'

services:
  php:
    build: .docker/php
    volumes: 
      - ./application:/var/www/html
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=${DB_DATABASE}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - APP_DEV_PERMITTED=true
      - PHP_DATE_TIMEZONE=UTC
    networks:
      - default
    working_dir: /var/www/html
  
  nginx:
    image: nginx:latest
    volumes:
      - .docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html
    labels:
      - "traefik.frontend.rule=Host:web.default.${HOST}"
      - "traefik.backend=nginx"
    networks:
      - default

  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  cache:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_CHARSET: "UTF8"
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - default

  node:
    image: node:8
    environment:
      YARN_CACHE_FOLDER: '/home/node/.yarn-cache'
    user: root
    volumes:
      - ./application:/var/www/html
    working_dir: /var/www/html

  se:
    hostname: selenium
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - default

  zoo_node_1:
    image: zookeeper
    container_name: zoo_node_1
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo_node_1:2888:3888 server.2=zoo_node_2:2888:3888 server.3=zoo_node_3:2888:3888
    networks:
      - default

  zoo_node_2:
    image: zookeeper
    container_name: zoo_node_2
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo_node_1:2888:3888 server.2=zoo_node_2:2888:3888 server.3=zoo_node_3:2888:3888
    networks:
      - default

  zoo_node_3:
    image: zookeeper
    container_name: zoo_node_3
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo_node_1:2888:3888 server.2=zoo_node_2:2888:3888 server.3=zoo_node_3:2888:3888
    networks:
      - default

  nifi:
    image: xemuliam/nifi
    container_name: nifi
    environment:
      IS_CLUSTER_NODE: 1
      ZK_NODES_LIST: 'zoo_node_1,zoo_node_2,zoo_node_3'
    volumes:
      - ./etc/nifi/conf:/opt/nifi/conf
    ports:
      - "9090:8080"
    networks:
      - default

volumes:
  sylius:
    driver_opts:
      type: none
      device: application
      o: bind

networks:
  default: ~
