<?php

namespace App\Repository\RV;
use Doctrine\ORM\EntityRepository;

/**
 * AfeCostReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfeCostReportRepository extends EntityRepository
{
    public function getByProject($project)
    {
        return $this
            ->createQueryBuilder('r')
            ->select('r')
            ->where('r.project = :project')
            ->setParameter('project', $project->getId())
           ;
    }

    public function getTotals($project)
    {
        return $this
            ->createQueryBuilder('r')
            ->select('sum(r.afeEstimate) as totalAfeEstimate, sum(r.fieldEstimate) as totalFieldEstimate')
            ->where('r.project = :project')
            ->setParameter('project', $project->getId())
            ->getQuery()
            ->getScalarResult()
           ;
    }
}
