<?php

namespace App\Repository\RV;

/**
 * CasingBowlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasingBowlRepository extends \Doctrine\ORM\EntityRepository
{
}
