<?php

namespace App\Repository\RV;

/**
 * CasingSegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasingSegmentRepository extends \Doctrine\ORM\EntityRepository
{
}
