<?php

namespace App\Repository\RV;

use App\Entity\RV\Licence;
use App\Entity\RV\ManPowerReport;

/**
 * ManPowerReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManPowerReportRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Licence $licence
     * @return array|ManPowerReport[]
     */
    public function findByLicence(Licence $licence)
    {
        $reports = $this->createQueryBuilder('p')
            ->innerJoin('t.dailyReport', 'dr')
            ->innerJoin('dr.event', 'e')
            ->where('IDENTITY(e.licence) = :licence')
            ->setParameter('licence', $licence)
            ->orderBy('dr.date', 'desc')
            ->addOrderBy('t.startTime', 'desc')
            ->getQuery()
            ->getResult();

        return $reports;
    }
}
