<?php

namespace App\Repository\RV;

/**
 * MidnightSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MidnightSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
