<?php

namespace App\Repository\RV;
use App\Entity\RV\AfeCostReport;

/**
 * MudExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MudExtraRepository extends \Doctrine\ORM\EntityRepository
{
    const ALIAS = 'mex';

    public function getMudExtraSummary($report)
    {
        return $this
            ->createQueryBuilder('me')
            ->select('me as mudExtra, SUM(me.cost) as cost')
            ->leftJoin('me.afeCostReport', 'afeCostReport')
            ->leftJoin('afeCostReport.afeAccount', 'afeAccount')
            ->where('me.report = :report')
            ->setParameter('report', $report->getId())
            ->groupBy('me.vendor, me.ticket, afeAccount.number')
               ->getQuery()
               ->getResult()
           ;
    }

    public function getSummary($project)
    {
        return $this
            ->createQueryBuilder('me')
            ->select('me')
            ->leftJoin('me.report', 'report')
            ->where('report.project = :project')
            ->setParameter('project', $project->getId())
            ->orderBy('report.date', 'desc')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getTotalCostByAfeCostReport(AfeCostReport $afeCostReport)
    {
        return $this->createQueryBuilder(self::ALIAS)
            ->select(sprintf('SUM(%s.cost) as amount', self::ALIAS))
            ->where(sprintf('%s.afeCostReport = :report', self::ALIAS))
            ->setParameter('report', $afeCostReport)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
