<?php

namespace App\Repository\RV;

/**
 * MudUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MudUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
