<?php

namespace App\Repository\RV;

/**
 * MudUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MudUsageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMudUsageSummary($report)
    {
        return $this
            ->createQueryBuilder('mu')
            ->select('mu as mudUsage, SUM(product.cost * mu.used) as cost')
            ->leftJoin('mu.product', 'product')
            ->leftJoin('product.afeCostReport', 'afeCostReport')
            ->leftJoin('afeCostReport.afeAccount', 'afeAccount')
            ->where('mu.report = :report')
            ->setParameter('report', $report->getId())
            ->groupBy('product.vendor, product.ticket, afeAccount.number')
               ->getQuery()
               ->getResult()
           ;
    }

    public function getNextReports($report, $product)
    {
        return $this
            ->createQueryBuilder('mu')
            ->select('mu')
            ->leftJoin('mu.product', 'product')
            ->leftJoin('mu.report', 'report')
            ->where('report.date >= :date')
            ->andWhere('mu.product = :product')
            ->setParameters([
                'date'      => $report->getDate(),
                'product'   => $product->getId()
            ])
            ->orderBy('report.date', 'asc')
            ->getQuery()
            ->getResult()
        ;
    }
}
