<?php

namespace App\Repository\RV;

/**
 * RigInspectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RigInspectionRepository extends \Doctrine\ORM\EntityRepository
{
}
