<?php

namespace App\Repository\RV;

/**
 * WeatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherRepository extends \Doctrine\ORM\EntityRepository
{
}
